#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Contao\Docs\LinkChecker\CheckCommand;

ini_set('display_errors', '1');
ini_set('display_startup_errors', '1');
error_reporting(E_ALL);

$checkCommand = new CheckCommand();

$application = new Application();
$application->add($checkCommand);
$application->setDefaultCommand($checkCommand->getName(), true);
$application->run();
