#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Contao\Docs\Normalizer\NormalizeCommand;

ini_set('display_errors', '1');
ini_set('display_startup_errors', '1');
error_reporting(E_ALL);

$normalizeCommand = new NormalizeCommand();

$application = new Application();
$application->add($normalizeCommand);
$application->setDefaultCommand($normalizeCommand->getName(), true);
$application->run();
