contentDir: '../docs'
title: 'Contao Documentation'
theme: 'hugo-theme-relearn'
canonifyURLs: true
enableGitInfo: true
disablePathToLower: true
outputs:
  home: [html, rss, OpenSearchXML]
markup:
  goldmark:
    parser:
      autoHeadingIDType: blackfriday
    renderer:
      unsafe: true
  tableOfContents:
    endLevel: 3
  highlight:
    noClasses: false
outputFormats:
  OpenSearchXML:
    baseName: search
    isPlainText: true
    mediaType: application/opensearchdescription+xml
    protocol: bep://
mediaTypes:
  application/opensearchdescription+xml:
    suffixes:
      - xml
imageEffects:
  shadow: true
