en:
  languageName: English
  weight: 1
  params:
    documentation_label_overview: 'More documentation on'
    documentation_label_website: 'More about Contao on'  
    documentation_label_switch: 'Go to the developer documentation'
de:
  languageName: Deutsch
  weight: 2
  title: 'Contao Handbuch'
  params:
    documentation_label: 'Handbuch'
    documentation_label_overview: 'Weitere Dokumentationen auf'
    documentation_label_website: 'Mehr über Contao auf'
    documentation_label_switch: 'Zur Entwickler Dokumentation'