#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Contao\Docs\DeeplTranslator\DeeplCommand;
use Contao\Docs\DeeplTranslator\FixupCommand;

ini_set('display_errors', '1');
ini_set('display_startup_errors', '1');
error_reporting(E_ALL);

$application = new Application();
$application->add(new DeeplCommand());
$application->add(new FixupCommand());
$application->run();
